Repository cshangout/CS-Hangout-Website, pull requests merged in 2023-01, with the labels that each got.

#20 15 create login text box for username and password
  client/src/App.test.js
  client/src/Authentication/AuthLandingPage.js
  client/src/Login/Login.css
  client/src/Login/Login.js
  client/src/__test__/Login.test.js
  package-lock.json
Labels: good first issue

#26 Created .env files with non-secret info for development
  client/.env
  client/.env.development
  client/.env.production
  client/public/index.html
  server/Server.API/Properties/launchSettings.json
Labels: enhancement

#29 Created constants file for strings/magic numbers
  client/src/Login/Login.js
  client/src/__helpers__/Constants.js
Labels: enhancement

#37 Create auth endpoint and dtos. Create user repository
  database/Users/create_user_table.sql
  server/Common.Tests/Common.Tests.csproj
  server/Common/Authentication/IUserTokenService.cs
  server/Common/Authentication/UserTokenService.cs
  server/Common/Common.csproj
  server/Server.API/Controllers/AuthController.cs
  server/Server.API/Properties/launchSettings.json
  server/Server.API/Server.API.csproj
  server/Server.API/Startup.cs
  server/Server.API/appsettings.Local.json
  server/Server.Infrastructure/Data/DataContext.cs
  server/Server.Infrastructure/Data/IDataContext.cs
  server/Server.Infrastructure/Entities/IEntity.cs
  server/Server.Infrastructure/Entities/User.cs
  server/Server.Infrastructure/Repositories/IUserRepository.cs
  server/Server.Infrastructure/Repositories/UserRepository.cs
  server/Server.Infrastructure/Server.Infrastructure.csproj
  server/Server.Tests/API/Controllers/AuthControllerTests.cs
  server/Server.Tests/Server.Tests.csproj
Labels: feature

#39 36 create token and user repository
  client/.env
  client/src/Login/Login.js
  server/.gitignore
  server/Common.Tests/Common.Tests.csproj
  server/Common.Tests/Usings.cs
  server/Common/Authentication/IUserTokenService.cs
  server/Common/Authentication/UserTokenService.cs
  server/Common/Common.csproj
  server/Common/Logging/ConfigureSerilog.cs
  server/Server.API/.gitignore
  server/Server.API/Controllers/AuthController.cs
  server/Server.API/Features/Authentication/Authentication.cs
  server/Server.API/Features/Logging/ConfigureSerilog.cs
  server/Server.API/Features/Settings/ConfigureAppSettings.cs
  server/Server.API/Program.cs
  server/Server.API/Properties/launchSettings.json
  server/Server.API/Server.API.csproj
  server/Server.API/Startup.cs
  server/Server.API/appsettings.Local.json
  server/Server.Infrastructure/Authentication/Roles/Roles.cs
  server/Server.Infrastructure/DTOs/ErrorDto.cs
  server/Server.Infrastructure/DTOs/LoginDto.cs
  server/Server.Infrastructure/DTOs/RegisterDto.cs
  server/Server.Infrastructure/DTOs/UserDto.cs
  server/Server.Infrastructure/Data/DataContext.cs
  server/Server.Infrastructure/Data/IDataContext.cs
  server/Server.Infrastructure/Entities/User.cs
  server/Server.Infrastructure/Entities/Users/User.cs
  server/Server.Infrastructure/Entities/Users/UserRoles.cs
  server/Server.Infrastructure/Mappers/IUserMapper.cs
  server/Server.Infrastructure/Mappers/UserMapper.cs
  server/Server.Infrastructure/Repositories/IUserRepository.cs
  server/Server.Infrastructure/Repositories/UserRepository.cs
  server/Server.Infrastructure/Repositories/Users/IUserRepository.cs
  server/Server.Infrastructure/Repositories/Users/UserRepository.cs
  server/Server.Infrastructure/Server.Infrastructure.csproj
  server/Server.Tests/API/Controllers/AuthControllerTests.cs
  server/Server.Tests/Server.Tests.csproj
  server/Server.Tests/TestData/Dtos/TestLoginDto.cs
  server/server.sln
Labels: feature

#48 Unit tests for auth controller
  client/src/Login/Login.js
  server/Server.API/Controllers/AuthController.cs
  server/Server.API/Program.cs
  server/Server.Infrastructure/DTOs/LoginDto.cs
  server/Server.Infrastructure/Repositories/Users/IUserRepository.cs
  server/Server.Infrastructure/Repositories/Users/UserRepository.cs
  server/Server.Tests/API/Controllers/AuthControllerTests.cs
  server/Server.Tests/Server.Tests.csproj
  server/Server.Tests/TestData/Dtos/TestLoginDto.cs
  server/Server.Tests/TestData/Dtos/TestRegisterDto.cs
  server/Server.Tests/TestData/Dtos/TestUserDto.cs
  server/Server.Tests/TestData/Entities/TestUser.cs
  server/Server.Tests/UnitTest1.cs
Labels: enhancement

#51 browser router that directs to app main page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/__test__/BrowserRouter.test.js
  client/src/index.js
  package-lock.json
Labels: feature

#52 44 create registration route
  client/public/favicon.ico
  client/src/Header/Header.js
  client/src/index.js
  client/src/logo.svg
Labels: feature
